version: '3.7'
services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./etc:/etc/trino
    networks:
      - trino-network

  metastore-db:
    image: postgres:14
    container_name: metastore-db
    hostname: metastore-db
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
    volumes:
      - metastore-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - trino-network

  hive-metastore:
    build: ./metastore
    container_name: hive-metastore
    hostname: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/hive/conf/metastore-site.xml:ro
    command: ["/bin/bash", "/opt/hive/conf/entrypoint.sh"]
    environment:
      DB_DRIVER: postgres
      HIVE_METASTORE_DB_TYPE: postgres
      METASTORE_DB_HOSTNAME: metastore-db
      METASTORE_DB_PORT: 5432
      METASTORE_DB_NAME: metastore
      METASTORE_DB_USER: hive
      METASTORE_DB_PASSWORD: hive
      SERVICE_NAME: metastore
    depends_on:
      - metastore-db
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 9083"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - trino-network

  minio:
    image: 'minio/minio:latest'
    hostname: minio
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data
    networks:
      - trino-network

  # SPARK CLUSTER
  spark-master:
    build: ./spark
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    command: bash -c "/opt/spark/sbin/start-master.sh; tail -f /opt/spark/logs/*"
    ports:
      - "8180:8080"   # Spark Web UI
      - "7077:7077"   # Spark master port
    volumes:
      - spark-events:/opt/spark/spark-events
      - ./spark/conf:/opt/spark/conf
    networks:
      - trino-network

  spark-worker:
    build: ./spark
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
    command: bash -c "/opt/spark/sbin/start-worker.sh spark://spark-master:7077; tail -f /opt/spark/logs/*"
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Worker UI
    volumes:
      - spark-events:/opt/spark/spark-events
      - ./spark/conf:/opt/spark/conf
    networks:
      - trino-network

  spark-history:
    build: ./spark
    container_name: spark-history
    hostname: spark-history
    environment:
      - SPARK_HISTORY_OPTS=-Dspark.history.fs.logDirectory=/opt/spark/spark-events
    command: bash -c "/opt/spark/sbin/start-history-server.sh && tail -f /opt/spark/logs/*"
    ports:
      - "18080:18080"   # Spark History Server UI
    volumes:
      - spark-events:/opt/spark/spark-events
    networks:
      - trino-network
    depends_on:
      - spark-master
      - spark-worker  

  notebooks:
    build: ./jupyter
    container_name: notebooks
    hostname: notebooks
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jupyter/notebooks
    networks:
      - trino-network
    depends_on:
      - spark-master

volumes:
  minio-data:
    driver: local
  metastore-db:  
  spark-events:

networks:
  trino-network:
    driver: bridge